web:
  build: .
  command: 'bash -c ''bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}'''
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
  volumes:
    - '.:/app/user'

